// Pakistani Cities
export const PAKISTANI_CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Gujranwala',
  'Hyderabad',
  'Bahawalpur',
  'Sargodha',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Jhang',
  'Rahim Yar Khan',
  'Gujrat',
  'Mardan',
  'Kasur',
  'Mingora',
  'Dera Ghazi Khan',
  'Sahiwal',
  'Nawabshah',
  'Okara',
  'Mirpur Khas',
  'Chiniot',
  'Kamoke',
  'Sadiqabad',
  'Burewala',
  'Jacobabad',
  'Muzaffargarh',
  'Khanpur',
  'Gojra',
  'Mandi Bahauddin',
  'Abbottabad',
  'Turbat',
  'Dadu',
  'Bahawalnagar',
  'Khanewal',
  'Shikarpur',
  'Hafizabad',
  'Kohat',
  'Jhelum',
  'Muridke',
  'Karak',
  'Khushab',
  'Dera Ismail Khan',
  'Chaman'
];

// Pakistani Provinces and Territories
export const PAKISTANI_PROVINCES = [
  'Punjab',
  'Sindh',
  'Khyber Pakhtunkhwa',
  'Balochistan',
  'Gilgit-Baltistan',
  'Azad Kashmir',
  'Islamabad Capital Territory'
];
